#!/bin/sh
# based on https://wiki.ubuntu.com/DebuggingProgramCrash
sudo apt install ubuntu-dbgsym-keyring
# on Ubuntu before 18.04:
# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F2EDC64DC5AEE1F6B9C621F0C8CAB6595FDFF622
printf "deb http://ddebs.ubuntu.com $(lsb_release -cs)%s main restricted universe multiverse\\n" "" "-updates" \
    | sudo tee /etc/apt/sources.list.d/ddebs.list
sudo apt update
