#!/usr/bin/python3
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Tool to analyze Docker images.

Usage:
  analyze-docker-image image:tag outdir/

This will use `docker save` to dump the container as an OCI image into a file
in ~/.cache/, and then create

  outdir/layer/00/
  outdir/layer/01/
  outdir/layer/02/
  outdir/layer/NN/

with the contents of each layer, an

  outdir/LAYERS.txt

with a list of the layers (and docker commands that produced them), and a

  outdir/rootfs/

with a symlink tree to files from each individual layer.

See https://github.com/opencontainers/image-spec/ for the spec.
"""

from __future__ import annotations

import argparse
import datetime
import io
import json
import os
import pathlib
import shlex
import shutil
import subprocess
import sys
import tarfile
from dataclasses import dataclass
from functools import cached_property
from typing import IO, Any, Iterable, Iterator, Self, TextIO


CACHE_DIR = pathlib.Path('~/.cache/docker-images').expanduser()

parser = argparse.ArgumentParser(description="Tool to analyze Docker images")
parser.add_argument(
    "image",
    help='image name with optional tag',
)
parser.add_argument(
    "output_dir",
    nargs='?',
    help='directory to contain the extracted image contents',
)
parser.add_argument(
    "-f", "--force",
    help='overwrite output directory if it exists',
    action='store_true',
)
parser.add_argument(
    "--no-extract",
    help='skip extracting the layers',
    action='store_true',
)
parser.add_argument(
    "--no-rootfs",
    help='skip creating the rootfs symlink tree',
    action='store_true',
)

parser.add_argument(
    "--debug",
    help='print verbose debug information',
    action='store_true',
)


@dataclass
class UI:
    debug: bool = False

    def info(self, msg: str) -> None:
        print(msg)

    def output(self, msg: str = '', *, file: TextIO) -> None:
        if self.debug:
            print(" ", msg)
        print(msg, file=file)


def main() -> None:
    args = parser.parse_args()

    ui = UI(debug=args.debug)

    info = docker_inspect(ui, args.image)
    if not info:
        sys.exit(f'Image {args.image} not found')

    if not args.output_dir:
        args.output_dir = args.image.rpartition('/')[-1]
    output_dir = pathlib.Path(args.output_dir)
    if (
        output_dir.exists()
        and not is_empty_directory(output_dir)
        and not args.force
    ):
        sys.exit(
            f'{fmt_path(output_dir)} already exists, refusing to overwrite'
        )

    size = info[0]["Size"]
    ui.info(f'Image size estimate is {fmt_size(size)}')

    cache_file = CACHE_DIR.joinpath(args.image + '.tar')
    cache_file.parent.mkdir(parents=True, exist_ok=True)
    if cache_file.exists():
        size = cache_file.stat().st_size
        ui.info(f'Image already cached in {fmt_path(cache_file)}'
                f' ({fmt_size(size)})')
    else:
        save_image_to_cache(ui, args.image, cache_file, size)

    image = DockerImage(cache_file)
    output_dir.mkdir(parents=True, exist_ok=True)
    extract_json_file(
        ui, image.oci_layout, output_dir.joinpath('oci-layout.json')
    )
    extract_json_file(
        ui, image.oci_index, output_dir.joinpath('oci-index.json')
    )
    extract_json_file(
        ui, image.oci_manifest, output_dir.joinpath('oci-manifest.json')
    )
    extract_json_file(ui, image.config, output_dir.joinpath('config.json'))
    extract_json_file(
        ui, image.docker_manifest, output_dir.joinpath('docker-manifest.json')
    )
    extract_json_file(
        ui,
        image.docker_repositories,
        output_dir.joinpath('docker-repositories.json'),
    )
    write_layer_history(ui, image, output_dir)
    if not args.no_extract:
        extract_layers(ui, image, output_dir)
    if not args.no_rootfs:
        create_merged_rootfs(ui, image, output_dir)
    ui.info(f'Created {fmt_path(output_dir)}/')


def extract_json_file(
    ui: UI, data: dict | list, output_path: pathlib.Path
) -> None:
    pprint_json(ui, data, file=output_path.open('w'))


def extract_layers(
    ui: UI, image: DockerImage, output_dir: pathlib.Path
) -> None:
    for layer in image.layers:
        with layer.open() as tf:
            count = len(tf.getnames())
            ui.info(
                f'Layer {layer.number}: {layer.digest}'
                f' ({fmt_size(layer.size)}, {fmt_count(count, "files")})'
            )
            tf.extractall(
                output_dir.joinpath('layers', layer.number),
                filter=filter_existing,
            )


def filter_existing(
    member: tarfile.TarInfo, dest_path: str
) -> tarfile.TarInfo | None:
    path = pathlib.Path(dest_path, member.name.lstrip('/' + os.path.sep))
    if (
        member.issym()
        and path.exists(follow_symlinks=False)
        and str(path.readlink()) == member.linkname
    ):
        # assume it was already extracted
        # we have to check this early before calling .tar_filter() because
        # the default filter will do an os.path.realpath() and follow the
        # actual symlink and that can fail with an OutsideDestinationError()
        return None
    member = tarfile.tar_filter(member, dest_path)
    if member is None:
        return None
    if path.exists() and path.stat().st_size == member.size:
        # assume it was already extracted
        return None
    return member


def create_merged_rootfs(
    ui: UI, image: DockerImage, output_dir: pathlib.Path
) -> None:
    tree = SymlinkTree()
    for layer in image.layers:
        for file in layer.files:
            # XXX: should handle whiteouts before newly added files, according
            # to spec, even if whiteout appears later
            tree.add(file, f'layers/{layer.number}/{file}')
    tree.materialize(ui, output_dir.joinpath('rootfs'))


def write_layer_history(
    ui: UI, image: DockerImage, output_dir: pathlib.Path
) -> None:
    if ui.debug:
        ui.info('Container history:\n')
    with output_dir.joinpath('LAYERS.txt').open('w') as fp:
        prev_timestamp = None
        prev_hdr = None
        layer_idx = 0
        for step in image.history:
            timestamp = datetime.datetime.fromisoformat(step["created"])
            command = step["created_by"]
            comment = step.get("comment")
            empty_layer = step.get("empty_layer")

            if prev_timestamp:
                delta = timestamp - prev_timestamp
                if delta > datetime.timedelta(1):
                    ui.output(file=fp)
                    ui.output(
                        f"# ----- {fmt_timedelta(delta)} later -----",
                        file=fp,
                    )
            msg = [f'# {fmt_timestamp(timestamp)}']
            hdr = [fmt_timestamp(timestamp)]
            if comment:
                msg.append(comment)
                hdr.append(comment)
            if empty_layer:
                if hdr == prev_hdr:
                    msg = []
                else:
                    msg.append('(empty layer)')
            else:
                msg.append(f'(layers/{layer_idx:02})')
                layer_idx += 1
            if msg:
                if prev_timestamp:
                    ui.output(file=fp)
                ui.output(' '.join(msg), file=fp)
            ui.output(command, file=fp)
            prev_timestamp = timestamp
            prev_hdr = hdr
    if ui.debug:
        ui.info('')


def is_empty_directory(path: pathlib.Path) -> bool:
    return path.is_dir() and next(path.iterdir(), None) is None


def fmt_timestamp(ts: datetime.datetime) -> str:
    return ts.strftime('%Y-%m-%d %H:%M:%S')


def fmt_timedelta(delta: datetime.timedelta) -> str:
    if delta.days:
        return fmt_count(delta.days, 'days')
    elif delta.seconds:
        return fmt_count(delta.seconds, 'seconds')
    elif delta.microseconds:
        return fmt_count(delta.microseconds, 'microseconds')
    else:
        return '0 seconds'


def fmt_size(size: int) -> str:
    for unit in ['B', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB']:
        if size < 1024:
            return f'{size} {unit}'
        size //= 1024
    return f'{size}EiB'


def fmt_count(count: int, items: str, item: str = '') -> str:
    if not item:
        item = items[:-1]
    if count == 1:
        return f'{count} {item}'
    return f'{count} {items}'


def fmt_path(path: pathlib.Path) -> str:
    home = str(pathlib.Path.home()) + '/'
    if str(path).startswith(home):
        return '~/' + str(path).removeprefix(home)
    if str(path) == home:
        return '~/'
    return str(path)


def fmt_command(command: list[str]) -> str:
    return shlex.join(command)


def pprint_json(
    ui: UI, data: dict | list, *, file: TextIO | None = None
) -> None:
    text = json.dumps(data, indent=2, separators=(',', ': '))
    if file:
        ui.output(text, file=file)
    else:
        ui.info(text)


def pipe_to_file(
    ui: UI, command: list[str], output_file: pathlib.Path, size_hint: int
) -> None:
    pv = shutil.which('pv')
    ui.info(
        f'Running {fmt_command(command)}'
        f"{' | pv' if pv else ''}"
        f' > {fmt_path(output_file)}'
    )
    with output_file.with_suffix('.tmp').open('wb') as fp:
        if pv:
            pv_pipe = subprocess.Popen(
                ['pv', '-s', str(size_hint)], stdin=subprocess.PIPE, stdout=fp
            )
            output = pv_pipe.stdin
        else:
            pv_pipe = None
            output = fp
        result = subprocess.run(command, stdout=output)
    if pv_pipe:
        assert pv_pipe.stdin is not None
        pv_pipe.stdin.close()
        pv_pipe.wait()
    if result.returncode == 0:
        output_file.with_suffix('.tmp').rename(output_file)
    else:
        sys.exit('Failed to export the image')


def json_from_pipe(ui: UI, command: list[str]) -> dict:
    ui.info(f'Running {fmt_command(command)}')
    return json.loads(subprocess.run(command, capture_output=True).stdout)


def docker_inspect(ui: UI, image_name: str) -> dict:
    return json_from_pipe(ui, ['docker', 'inspect', '--', image_name])


def save_image_to_cache(
    ui: UI, image_name: str, cache_file: pathlib.Path, size_hint: int
) -> None:
    ui.info(f'Saving {image_name}...')
    pipe_to_file(
        ui, ['docker', 'save', '--', image_name], cache_file, size_hint
    )


@dataclass
class DockerImage:

    tar_path: pathlib.Path

    def __init__(self, tar_path: pathlib.Path) -> None:
        self.tar_path = tar_path
        self.tarfile = tarfile.open(tar_path)

    def close(self) -> None:
        self.tarfile.close()

    def __enter__(self) -> Self:
        return self

    def __exit__(self, *args) -> None:
        self.close()

    def blob_filename(self, digest: str) -> str:
        alg, colon, ref = digest.partition(':')
        assert alg == 'sha256' and colon == ':'
        return f'blobs/{alg}/{ref}'

    def open_member(self, filename: str) -> IO[bytes]:
        fp = self.tarfile.extractfile(filename)
        if fp is None:
            # This happens when the tar member is a directory or a device node
            raise tarfile.ReadError(f'{filename} is not a regular file')
        return fp

    def get_json(self, filename: str) -> Any:
        with self.open_member(filename) as fp:
            return json.load(fp)

    def get_json_from_digest(self, digest: str) -> dict:
        return self.get_json(self.blob_filename(digest))

    @cached_property
    def docker_manifest(self) -> list[dict]:
        # This is not part of the OCI image spec!  Docker uses it.
        return self.get_json('manifest.json')

    @cached_property
    def docker_repositories(self) -> dict:
        # This is not part of the OCI image spec!  Docker uses it.
        return self.get_json('repositories')

    @cached_property
    def oci_layout(self) -> dict:
        return self.get_json('oci-layout')

    @cached_property
    def oci_index(self) -> dict:
        return self.get_json('index.json')

    @cached_property
    def oci_manifest_digest(self) -> str:
        # XXX: multiarch images have multiple manifests
        return self.oci_index['manifests'][0]['digest']

    @cached_property
    def oci_manifest(self) -> dict:
        return self.get_json_from_digest(self.oci_manifest_digest)

    @cached_property
    def config(self) -> dict:
        # we could do
        #   return self.get_json(self.docker_manifest[0]['Config'])
        # or
        return self.get_json_from_digest(self.oci_manifest['config']['digest'])

    @cached_property
    def architecture(self) -> str:
        return self.config['architecture']

    @cached_property
    def exposed_ports(self) -> dict[str, dict]:
        return self.config['config']['ExposedPorts']

    @cached_property
    def environment(self) -> list[str]:
        return self.config['config']['Env']

    @cached_property
    def labels(self) -> dict[str, str]:
        return self.config['config']['Labels']

    @cached_property
    def history(self) -> dict:
        return self.config['history']

    @cached_property
    def layers(self) -> list[DockerImageLayer]:
        # We could do
        #   return [
        #       DockerImageLayer(self, filename, n)
        #       for n, filename in enumerate(self.docker_manifest[0]['Layers'])
        #   ]
        # or
        return [
            DockerImageLayer(
                self, self.blob_filename(layer['digest']), n, layer['size']
            )
            for n, layer in enumerate(self.oci_manifest['layers'])
        ]


class DockerImageLayer:

    def __init__(
        self,
        docker_image: DockerImage,
        filename: str,
        index: int,
        size: int | None = None,
    ) -> None:
        self.image = docker_image
        self.filename = filename
        self.index = index
        if size is not None:
            self.size = size
        # otherwise self.size will be computed by the cached property

    @cached_property
    def number(self) -> str:
        return f'{self.index:02}'

    @cached_property
    def digest(self) -> str:
        return self.filename.rpartition('/')[-1]

    @cached_property
    def source(self) -> dict:
        return self.image.docker_manifest[0]['LayerSources'][
            f'sha256:{self.digest}'
        ]

    @cached_property
    def size(self) -> int:
        return self.source['size']

    @cached_property
    def tarfile_in_memory(self) -> bytes:
        with self.image.open_member(self.filename) as fp:
            return fp.read()

    def open(self, buffer: bool = True) -> tarfile.TarFile:
        # If I don't buffer the nested tarfile in RAM,
        # I will get an error during seek.
        return tarfile.open(fileobj=io.BytesIO(self.tarfile_in_memory))

    @cached_property
    def files(self) -> list[str]:
        with self.open() as tf:
            return tf.getnames()


@dataclass
class SymlinkTree:

    root: dict[str, str | SymlinkTree]
    name: str

    def __init__(self, name: str = 'rootfs') -> None:
        self.root = {}
        self.name = name

    def __repr__(self) -> str:
        return f'SymlinkTree({self.name!r})'

    def add(self, name: str, target: str) -> None:
        if name == '.':
            return
        head, slash, tail = name.partition('/')
        if slash:
            assert not head.startswith('.wh.')
            match self.root.get(head):
                case SymlinkTree() as subtree:
                    pass
                case _:
                    subtree = SymlinkTree(f'{self.name}/{head}')
                    self.root[head] = subtree
            subtree.add(tail, target)
        else:
            if name.startswith('.wh.'):
                self.remove(name.removeprefix('.wh.'))
            else:
                match self.root.get(head):
                    case SymlinkTree():
                        pass
                    case _:
                        self.root[name] = target

    def remove(self, name: str) -> None:
        head, slash, tail = name.partition('/')
        if slash:
            assert not head.startswith('.wh.')
            subtree = self.root[head]
            assert isinstance(subtree, SymlinkTree)
            subtree.remove(tail)
        elif name == '.wh..opq':
            # .add('.wh..wh..opq') -> .remove('.wh..opq')
            self.root.clear()
        else:
            assert not name.startswith('.wh.')
            self.root.pop(name, None)

    def compute(
        self, where: pathlib.Path, prefix: str = '../'
    ) -> Iterator[tuple[pathlib.Path, str | None]]:
        yield (where, None)
        for name, target in self.root.items():
            match target:
                case SymlinkTree():
                    yield from target.compute(
                        where.joinpath(name), prefix + '../'
                    )
                case str():
                    yield (where.joinpath(name), prefix + target)

    def materialize(self, ui: UI, where: pathlib.Path) -> None:
        for symlink, target in self.compute(where):
            if target is None:
                symlink.mkdir(exist_ok=True)
            else:
                target_path = symlink.parent.joinpath(target)
                if target_path.is_symlink():
                    # suppose layer/00 has a ./bin -> usr/bin
                    # if we create rootfs/bin -> ../layer/00/usr/bin, then
                    # we won't be able to see usr/bin/x for any x added in
                    # layer/01 and later
                    # so we want symlinks to be copied directly to the rootfs
                    # without pointing to the original layer that added them
                    target = str(target_path.readlink())
                    if target.startswith('/'):
                        # symlink is <where>/<subpath>/name
                        # we disregard the final name and want to climb up to
                        # <where>/
                        back_to_root = '../' * (
                            len(symlink.relative_to(where).parents) - 1
                        )
                        target = back_to_root + target[1:]
                if symlink.is_symlink() and str(symlink.readlink()) != target:
                    symlink.unlink()
                try:
                    symlink.symlink_to(target)
                except FileExistsError:
                    assert symlink.is_symlink()
                    assert str(symlink.readlink()) == target
                else:
                    if ui.debug:
                        ui.info(f'  {symlink} -> {target}')


if __name__ == "__main__":
    try:
        main()
    except Exception:
        import pdb
        import readline  # noqa
        import traceback
        traceback.print_exc()
        pdb.post_mortem()
