#!/bin/bash
dir=$1
url=${2:?usage: autoclone directory git-url [--branch=...] [description]}
shift 2
git_clone_args=()
case "$1" in
    --branch=*)
        git_clone_args+=("$1")
        shift
        ;;
esac
what=${1:-${dir##*/}}
if ! [ -d "$dir" ]; then
    echo "To get $what do" 1>&2
    echo 1>&2
    echo "  git clone $url ${dir/#$HOME/\~}" "${git_clone_args[@]}" 1>&2
    echo 1>&2
    if [ -t 0 ]; then # stdin is a tty
        read -r -p "Would you like me to run that for you now? [y/N] " answer
        if [ "$answer" = "y" ]; then
            git clone "$url" "$dir" "${git_clone_args[@]}" || exit 1
        else
            exit 1
        fi
    else
        exit 1
    fi
fi
