#!/bin/sh
autoclone ~/blog fridge:git/newblog.git || exit 1

url=http://localhost:1313/blog/

# launch a browser after the web server starts up
({ wget --retry-connrefused -T 1 -O /dev/null $url && xdg-open $url; } >/dev/null 2>&1) &

make -C ~/blog preview
