#!/bin/bash
# Perhaps a script will make blogging easier for me

autoclone ~/blog fridge:git/newblog.git
cd ~/blog/content || exit 1

file=$1

case "$file" in
  *.*|"") ;;
  *) file=$file.md;;
esac

if test -n "$file" && ! test -f "$file"; then
  cat > "$file" << END
+++
title = "${1//-/ }"
tags = []
date = "$(date +%Y-%m-%dT%H:%M:%S%z|sed s/00$/:00/)"
draft = true
+++

END
fi

vim "$file"
