#!/bin/bash
# bzr diff with nice colours
if test -t 1 && test -x /usr/bin/colordiff; then
    # stdout is a tty
    exec bzr diff --diff-options=-p "$@" | colordiff | less -R
else
    exec bzr diff --diff-options=-p "$@"
fi
