#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = [
#   "pyinstaller",      # works with version 6.20.0
#   "python-debian",
# ]
# ///
"""
Usage:
  compare-pyinstaller-bundles file1 file2

Compares the set of libraries and modules included in executables produced by
pyinstaller --onefile.

Can extract the pyinstaller-made executables directly from .deb package files,
if there's only one packaged file in /usr/bin/ inside the .deb.
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from functools import cached_property
from types import TracebackType
from typing import IO, Collection

from debian.debfile import DebFile
from PyInstaller.archive.readers import CArchiveReader


parser = argparse.ArgumentParser(
    description=(
        "Compare the set of files included in pyinstaller-produced bundles"
    ),
)
parser.add_argument("file1")
parser.add_argument("file2", nargs='?')


class ArchiveReader:

    def __init__(self, filename: str) -> None:
        self.filename = filename
        self.archive = CArchiveReader(filename)
        # NB: if pyinstaller's internal API changes and it becomes a pain to
        # track I could switch to parsing the output of subprocess.run(['uvx',
        # '--from', 'pyinstaller', 'pyi-archive_viewer', '-br', filename])

    def __enter__(self) -> ArchiveReader:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType,
    ) -> None:
        pass

    @cached_property
    def bundle(self) -> set[str]:
        return set(self.archive.toc.keys())

    @cached_property
    def nested_bundle(self) -> set[str]:
        if not self.pyz_filename:
            return set()
        return self.get_nested_bundle(self.pyz_filename)

    @cached_property
    def bundle_filename(self) -> str:
        return self.filename

    @cached_property
    def pyz_filename(self) -> str | None:
        return self.find_pyz_file()

    def find_pyz_file(self) -> str | None:
        pyz_files = [name for name in self.bundle if name.endswith('.pyz')]
        if len(pyz_files) == 1:
            return next(iter(pyz_files))
        elif not pyz_files:
            print(f"No .pyz files in {self.filename}")
        else:
            print_set(f"Multiple .pyz files in {self.filename}:", pyz_files)
        return None

    def get_nested_bundle(self, inner_filename: str) -> set[str]:
        archive = self.archive.open_embedded_archive(inner_filename)
        return set(archive.toc.keys())


class DebArchiveReader:

    def __init__(self, filename: str) -> None:
        self.filename = filename
        self.deb = DebFile(filename)
        self.temp_file: IO[bytes] | None = None

    def __enter__(self) -> DebArchiveReader:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType,
    ) -> None:
        self.deb.close()
        if self.temp_file:
            self.temp_file.close()

    @cached_property
    def archive(self) -> ArchiveReader:
        assert self.pyinstaller_file is not None
        self.temp_file = tempfile.NamedTemporaryFile(
            prefix='compare-pyinstaller-bundles-'
        )
        shutil.copyfileobj(
            self.deb.data.get_file(self.pyinstaller_file), self.temp_file
        )
        self.temp_file.seek(0)
        return ArchiveReader(self.temp_file.name)

    @cached_property
    def bundle(self) -> set[str]:
        return self.archive.bundle

    @cached_property
    def nested_bundle(self) -> set[str]:
        return self.archive.nested_bundle

    @cached_property
    def bundle_filename(self) -> str:
        return f'{self.filename}/{self.pyinstaller_file}'

    @cached_property
    def pyz_filename(self) -> str | None:
        return self.archive.pyz_filename

    @cached_property
    def pyinstaller_file(self) -> str | None:
        return self.find_pyinstaller_file()

    def find_pyinstaller_file(self) -> str | None:
        files = [
            name for name in self.deb.data if name.startswith('./usr/bin/')
        ]
        if len(files) == 1:
            return next(iter(files))
        elif not files:
            print(
                f'Did not find any binaries in usr/bin inside {self.filename}'
            )
        else:
            print_set(f'Found more than one binary in {self.filename}:', files)
        return None


def read_bundle(filename: str) -> ArchiveReader | DebArchiveReader:
    try:
        if filename.endswith('.deb'):
            return DebArchiveReader(filename)
        else:
            return ArchiveReader(filename)
    except OSError as e:
        sys.exit(str(e))


def print_set(title: str, items: Collection[str]) -> None:
    if not items:
        return
    print(title)
    for item in sorted(items):
        print(f'  {item}')


def main():
    args = parser.parse_args()
    if not args.file2:
        with read_bundle(args.file1) as bundle:
            print_set(f"Files in {bundle.bundle_filename}:", bundle.bundle)
            print_set(
                f"Modules in {bundle.bundle_filename}/{bundle.pyz_filename}:",
                bundle.nested_bundle,
            )
        return
    with (
        read_bundle(args.file1) as bundle1,
        read_bundle(args.file2) as bundle2,
    ):
        if bundle1.bundle == bundle2.bundle:
            # as if this would ever happen
            print("Both bundles have the same files")
        else:
            print_set(
                f"Only in {bundle1.bundle_filename}:",
                bundle1.bundle - bundle2.bundle,
            )
            print_set(
                f"Only in {bundle2.bundle_filename}:",
                bundle2.bundle - bundle1.bundle,
            )
        if bundle1.nested_bundle == bundle2.nested_bundle:
            # as if this would ever happen
            print("Both nested bundles have the same modules")
        else:
            print_set(
                f"Only in {bundle1.bundle_filename}/{bundle1.pyz_filename}:",
                bundle1.nested_bundle - bundle2.nested_bundle,
            )
            print_set(
                f"Only in {bundle2.bundle_filename}/{bundle2.pyz_filename}:",
                bundle2.nested_bundle - bundle1.nested_bundle,
            )


if __name__ == "__main__":
    try:
        main()
    except Exception:
        import pdb
        import readline  # noqa
        import traceback
        traceback.print_exc()
        pdb.post_mortem()
