#!/bin/bash
if [ -d .git ] && ! grep -q '^tags$' .git/info/exclude; then
    echo tags >> .git/info/exclude
fi

ctags=/usr/bin/ctags
if [ -x ~/src/ctags/ctags ]; then
    ctags=~/src/ctags/ctags
elif [ -x /usr/bin/ctags-universal ]; then
    ctags=/usr/bin/ctags-universal
fi

# exuberant-ctags dunno-which-version generates 'i' kind for "from module
# import name", IIRC?  And I exclude that with --python-kinds=-i from ~/.ctags.
#
# universal-ctags 5.9 generates 'x' kind for "from module import name"
# universal-ctags 6.2 generates 'Y' kind for those imports
# if you try to pass --kinds-python=-x/-Y for the wrong ctags version, it complains
#   "Warning: Unsupported kind: 'x' for --kinds-python option"
# or
#   "Warning: Unsupported kind: 'Y' for --kinds-python option"
# and I don't like that, so let's autodetect.
if $ctags --list-kinds=python | grep -q ^Y; then
    bad_kind=(--kinds-python=-Y)
elif $ctags --list-kinds=python | grep -q ^x; then
    bad_kind=(--kinds-python=-x)
else
    bad_kind=()
fi

exec $ctags "${bad_kind[@]}" "$@"
