#!/bin/sh
dconf load / <<EOF
[org/gnome/settings-daemon/plugins/media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0]
binding='<Super>g'
command='gtimelog'
name='Open gtimelog'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1]
binding='<Super>t'
command='gnome-terminal'
name='Open terminal'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3]
binding='<Super>c'
command='connect-headset'
name='Connect Headset'

EOF
