#!/bin/sh
NICE="nice -n 10"
test -x /usr/bin/ionice && NICE="$NICE ionice -c3"
if [ -x /usr/bin/apt ]; then
    $NICE sudo apt full-upgrade -u -f --auto-remove "$@"
else
    $NICE sudo apt-get dist-upgrade -u -f --auto-remove "$@"
fi
# @#%@#% kernel updates that leave an autoremovable old version but only after
# the transaction ends
$NICE sudo apt-get auto-remove "$@"
