#!/bin/sh
# synaptics
##xinput set-int-prop 'SynPS/2 Synaptics TouchPad' 'Synaptics Two-Finger Scrolling' 8 1 1
# libinput
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Scroll Method Enabled' --type=int --format=8 1 0 0
