#!/bin/bash
set -eu

if [[ $# -eq 0 || $1 = --help ]]; then
    echo "usage: for-all-projects command [args ...]" 1>&2
    exit 1
fi

cd ~/projects || {
    # shellcheck disable=SC2088
    echo '~/projects is missing, aborting' 1>&2
    echo "(cd ~/src/mg-infra && ansible-playbook projects.yml)" 1>&2
    exit 1
}

purple=$(tput setaf 5)
red=$(tput setaf 1)
reset=$(tput sgr0)
rc=0
failures=()
for project in *; do
    printf '\n%s+ %s%s\n\n' "$purple" "$project" "$reset"
    (cd "$project" && "$@") || { rc=1; failures+=("$project"); }
done

if [[ ${#failures[@]} -ne 0 ]]; then
    printf '\n%s+++ FAILED: %s%s\n' "$red" "${failures[*]}" "$reset" 1>&2
fi

exit $rc
