#!/bin/sh
# fix bogus author emails in a git repository

test -d .git || {
  echo "$0: $PWD is not a Git repository" 1>&2
  exit 1
}

echo "Before:"
git shortlog -se
echo
git filter-branch -f --env-filter '
  if [ "$GIT_AUTHOR_EMAIL" = "laurynas@plastic" ]; then
      GIT_AUTHOR_EMAIL="laurynas@pov.lt";
  fi;
  if [ "$GIT_AUTHOR_EMAIL" = "" -a "$GIT_AUTHOR_NAME" = "ijk" ]; then
      # https://launchpad.net/~ijk, contributed 3 patches to gtimelog
      GIT_AUTHOR_EMAIL="M8R-8mxf0d@mailinator.com";
  fi;
  if [ "$GIT_AUTHOR_EMAIL" = "" -o \
       "$GIT_AUTHOR_EMAIL" = "mg@mgdesktop" -o \
       "$GIT_AUTHOR_EMAIL" = "mgedmin@plant" -o \
       "$GIT_AUTHOR_NAME" = "(no author)" -o \
       "$GIT_AUTHOR_NAME" = "mg" ]; then
      GIT_AUTHOR_NAME="Marius Gedminas";
      GIT_AUTHOR_EMAIL=marius@gedmin.as;
  fi;
  export GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL;
  if [ "$GIT_COMMITTER_EMAIL" = "" -o "$GIT_COMMITTER_NAME" = "mg" ]; then
      GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME;
      GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL;
      export GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL;
  fi'
echo
echo "After:"
git shortlog -se
