#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = [
#   "pygit2",
#   "rich",
# ]
# ///
"""
Compare the histories of a single file in two git repositories.

Synopsis:
    git-find-similarities file1 file2

"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import pathlib
import sys
from collections.abc import Iterator
from dataclasses import dataclass
from functools import cached_property
from typing import TYPE_CHECKING, Self

from pygit2 import Repository
from pygit2.enums import ObjectType, SortMode
from rich.console import Console
from rich.text import Text
from rich.theme import Theme


if TYPE_CHECKING:
    from pygit2 import Blob, Commit, Oid, Tree


parser = argparse.ArgumentParser(
    description=(
        "Compare the histories of a single file in two git repositories"
    ),
)
parser.add_argument("file", nargs='+', type=pathlib.Path)


class Error(Exception):
    pass


def find_git_repo(
    pathname: pathlib.Path,
) -> tuple[Repository, pathlib.PurePath]:
    for parent in pathname.parents:
        if (candidate := parent.joinpath('.git')).exists():
            return Repository(candidate), pathname.relative_to(parent)
    raise Error(f'{pathname} is not inside a Git repository')


def walk_tree(tree: Tree, path: pathlib.PurePath) -> Blob:
    for name in path.parts:
        assert tree.type == ObjectType.TREE
        tree = tree[name]
    assert tree.type == ObjectType.BLOB
    return tree


def walk_history(repo: Repository) -> Iterator[Commit]:
    # newest to oldest
    yield from repo.walk(repo.head.target, SortMode.TIME)


class Versions:
    _oldest: dict[Oid, tuple[Commit, Blob]]

    def __init__(self) -> None:
        self._oldest = {}

    def add(self, commit: Commit, blob: Blob) -> None:
        self._oldest[blob.id] = (commit, blob)

    def __len__(self) -> int:
        return len(self._oldest)

    def all(self) -> Iterator[tuple[Commit, Blob]]:
        yield from self._oldest.values()

    def has_blob_with_id(self, oid: Oid) -> bool:
        return oid in self._oldest


def find_all_versions(
    repo: Repository, pathname: pathlib.PurePath
) -> Versions:
    versions = Versions()
    for commit in walk_history(repo):
        try:
            blob = walk_tree(commit.tree, pathname)
        except KeyError:
            pass
        else:
            versions.add(commit, blob)
    return versions


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def first_line(message: str) -> str:
    lines = message.splitlines()
    return lines[0] if lines else ''


@dataclass
class Target:
    repo: Repository
    relpath: pathlib.PurePath

    @classmethod
    def from_filename(cls, filename: pathlib.Pathname) -> Self:
        repo, relpath = find_git_repo(filename)
        return cls(repo, relpath)

    @property
    def fullpath(self) -> pathlib.Path:
        fullpath = pathlib.Path(self.repo.workdir, self.relpath)
        return fullpath

    @cached_property
    def versions(self) -> Versions:
        return find_all_versions(self.repo, self.relpath)

    def has_blob_with_id(self, oid: Oid) -> bool:
        return self.versions.has_blob_with_id(oid)


def format_path(pathname: pathlib.Path) -> str:
    try:
        relpath = pathname.relative_to(pathlib.Path.home())
        if relpath == '.':
            return '~'
        return f'~/{relpath}'
    except ValueError:
        return str(pathname)


THEME = Theme({
    'path': 'cyan',
    'number': 'green',
    'commit': 'green',
    'time': 'bright_blue',
    'message': 'bright_yellow',
    'hash': 'blue',
})


def print_versions(target: Target, all_targets: list[Target]) -> None:
    console = Console(theme=THEME)
    s = 's' if len(target.versions) != 1 else ''
    console.print(Text.assemble(
        (format_path(target.fullpath), 'path'), ' has ',
        (str(len(target.versions)), 'number'), f' version{s}',
    ))
    for commit, blob in target.versions.all():
        ctime = dt.datetime.fromtimestamp(
            commit.commit_time,
            tz=dt.timezone(dt.timedelta(minutes=commit.commit_time_offset)),
        )
        console.print(Text.assemble(
            '  ', (commit.short_id, 'commit'),
            ' ', (ctime.strftime('%Y-%m-%d %H:%M %z'), 'time'),
            ' ', (first_line(commit.message), 'message'),
        ))
        text = Text.assemble('    ', (sha256(blob.data), 'hash'))
        targets = [t for t in all_targets if t.has_blob_with_id(blob.id)]
        if len(targets) > 1:
            n = len(targets) - 1
            repositories = 'repositories' if n != 1 else 'repository'
            text += Text.assemble(
                ' (shared with ', (str(n), 'number'), f' other {repositories})'
            )
        console.print(text)
    console.print()


def main() -> None:
    args = parser.parse_args()
    try:
        all_targets = [
            Target.from_filename(filename)
            for filename in args.file
        ]
        for target in all_targets:
            print_versions(target, all_targets)
    except Error as e:
        sys.exit(str(e))


if __name__ == "__main__":
    main()
