#!/usr/bin/python
import sys, subprocess, re, os
charmap = '/usr/share/i18n/charmaps/UTF-8'
grep = 'grep'
if not os.path.exists(charmap) and os.path.exists(charmap + '.gz'):
    charmap += '.gz'
    grep = 'zgrep'
pipe = subprocess.Popen([grep, '-hi', '-e', '.*'.join(sys.argv[1:]), charmap],
                        stdout=subprocess.PIPE)
rx = re.compile(r'<U([0-9A-Fa-f]{4}|[0-9A-Fa-f]{8})>')
for line in pipe.stdout:
    print rx.sub(lambda m: unichr(int(m.group(1), 16)) + '\t' + m.group(0),
                 line).encode('UTF-8'),
