#!/bin/bash
autoclone ~/src/gtimelog2jira https://github.com/ProgrammersOfVilnius/gtimelog2jira || exit 1
if ! [ -e ~/.local/bin/gtimelog2jira ]; then
    pipx install -e ~/src/gtimelog2jira || exit 1
fi
exec ~/.local/bin/gtimelog2jira "$@"
