#!/bin/sh
# before oneiric
if [ -x /usr/bin/gconftool-2 ]; then
    gconftool-2 -s /desktop/gnome/peripherals/keyboard/delay -t int 250
fi
# starting with oneiric
# only problem is this seems to reset the value to the defaul sluggish 500ms, no matter what number I use :(
# I've no clue why
# OOH because I'm skipping the gsettings layer maybe?
##test -x /usr/bin/dconf && dconf write /org/gnome/settings-daemon/peripherals/keyboard/delay 250
if [ -x /usr/bin/gsettings ]; then
    # welp in xenial this key does not exist any more so what do I do?
    ##gsettings set org.gnome.settings-daemon.peripherals.keyboard delay 250
    # oh it's been moved to deprecated
    gsettings set org.gnome.settings-daemon.peripherals.keyboard.deprecated:/org/gnome/desktop/peripherals/keyboard/ delay 250
    # BTW how did I discover this magic?
    # dconf dump > /tmp/wtf1
    # use gnome-control-center to adjust the delay
    # dconf dump > /tmp/wtf2
    # diff -u /tmp/wtf1 /tmp/wtf2
    # so maybe dconf write /org/gnome/desktop/peripherals/keyboard/delay 250 would've been simpler
fi
