#!/bin/sh
url=${1?usage: $0 url}
logger -t irc-open-url "clicked <$url>"
# trim punctuation that follows the URL
fixed_url=${url%[,.?!]}
# trim surrounding parens
fixed_url=${fixed_url#(}
fixed_url=${fixed_url#)}
xdg-open "$fixed_url"
