#!/bin/sh
# do not run irc-tunnel if irssi is already running, that would kill its
# network connection!
# NB: this script is called irssi so pgrep will always find at least one such
# process running!
if [ "$(pgrep -c irssi)" -ge 2 ]; then
    irc-tunnel
fi
if [ -x ~/opt/irssi/bin/irssi ]; then
    exec ~/opt/irssi/bin/irssi "$@"
else
    exec /usr/bin/irssi "$@"
fi
