#!/usr/bin/python3
"""
Read a JSON list of records from stdin or file, format them as a table.
"""

import argparse
import enum
import json
import os
import sys
from collections import defaultdict
from functools import partial, partialmethod


parser = argparse.ArgumentParser(description=__doc__.strip())
parser.add_argument("filename", nargs='?', metavar="filename.json")
parser.add_argument(
    "-r",
    "--rename-columns",
    metavar="COL1=FIELD1,COL2=FIELD2,...",
    help="comma-separated list of column names and field names for them",
)
parser.add_argument(
    "-o",
    "--column-order",
    metavar="COL1,COL2,...",
    help="comma-separated list of field names for reordering columns",
)
parser.add_argument(
    "-s",
    "--sort",
    metavar="[,-]COL1,[-]COL2,...",
    help=(
        "comma-separated list of column names for sorting rows"
        " (a - prefix reverses the order)"
    ),
)


NULL = 'null'


class Color(enum.StrEnum):
    NONE = ''
    BLACK = '30'
    RED = '31'
    GREEN = '32'
    YELLOW = '33'
    BLUE = '34'
    PURPLE = '35'
    CYAN = '36'
    GREY = '37'
    DARK_GREY = f'1;{BLACK}'
    BRIGHT_RED = f'1;{RED}'
    BRIGHT_GREEN = f'1;{GREEN}'
    BRIGHT_BLUE = f'1;{BLUE}'
    WHITE = f'1;{GREY}'

    def ansi(self) -> str:
        if not self.value:
            return ''
        return f'\x1B[{self.value}m'

    def reset(self) -> str:
        return '\x1B[m'

    def wrap(self, s: object, width: int | None = None) -> str:
        if width is not None:
            s = str(s).ljust(width)
        else:
            s = str(s)
        if not self.value:
            return s
        return f'{self.ansi()}{s}{self.reset()}'


class ThemeColor(enum.StrEnum):
    TITLE = 'title'
    SEPARATOR = 'separator'
    STRING_VALUE = 'string_value'
    NUMERIC_VALUE = 'numeric_value'
    NULL_VALUE = 'null_value'
    OTHER_VALUE = 'other_value'


class Theme:
    _colors: dict[ThemeColor, Color] = {}

    def _format(
        self, _attr: ThemeColor, obj: object, /, width: int | None = None
    ) -> str:
        return self._colors.get(_attr, Color.NONE).wrap(obj, width=width)

    _formatter = partial(partialmethod, _format)

    title = _formatter(ThemeColor.TITLE)
    separator = _formatter(ThemeColor.SEPARATOR)
    string_value = _formatter(ThemeColor.STRING_VALUE)
    numeric_value = _formatter(ThemeColor.NUMERIC_VALUE)
    null = _formatter(ThemeColor.NULL_VALUE)
    other_value = _formatter(ThemeColor.OTHER_VALUE)


class ColorfulTheme(Theme):
    _colors = {
        ThemeColor.TITLE: Color.BRIGHT_BLUE,
        ThemeColor.SEPARATOR: Color.BRIGHT_BLUE,
        ThemeColor.STRING_VALUE: Color.GREEN,
        ThemeColor.NUMERIC_VALUE: Color.GREY,
        ThemeColor.NULL_VALUE: Color.DARK_GREY,
        ThemeColor.OTHER_VALUE: Color.GREY,
    }


class PlainTheme(Theme):
    pass


class Error(SystemExit):
    pass


def value2str(
    value: object, theme: Theme = PlainTheme(), width: int | None = None
) -> str:
    match value:
        case None:
            return theme.null(NULL, width=width)
        case str():
            return theme.string_value(value, width=width)
        case int() | float():
            return theme.numeric_value(value, width=width)
        case _:
            return theme.other_value(value, width=width)


def main():
    if (
        os.getenv('FORCE_COLOR')
        or sys.stdout.isatty() and not os.getenv('NO_COLOR')
    ):
        theme = ColorfulTheme()
    else:
        theme = PlainTheme()
    args = parser.parse_args()
    if not args.filename or args.filename == '-':
        if sys.stdin.isatty():
            parser.error('refusing to read from a terminal')
        records = json.load(sys.stdin)
    else:
        with open(args.filename) as f:
            records = json.load(f)

    if not isinstance(records, list):
        raise Error("json data is not a list")
    if not records:
        print(theme.null("no data"))
        return

    # mapping of column names to maximum widths
    # initialize all to 4 in case some rows have missing values
    columns = defaultdict(lambda: len(NULL))
    if args.column_order:
        for c in map(str.strip, args.column_order.split(',')):
            if c:
                columns[c]  # autovivify
    field2col = {}
    col2field = {}
    if args.rename_columns:
        for cf in args.rename_columns.split(","):
            col, _, field = cf.partition('=')
            col = col.strip()
            field = field.strip()
            field2col[field] = col
            col2field[col] = field
    for n, record in enumerate(records):
        if not isinstance(record, dict):
            raise Error(f"Item [{n}] is not an object")
        for k, v in record.items():
            c = field2col.get(k, k)
            columns[c] = max(columns[c], len(value2str(v)))
    for c, w in columns.items():
        columns[c] = max(w, len(c))

    if args.sort:
        for c in reversed(args.sort.split(',')):
            c = c.strip()
            if not c:
                continue
            reverse = c.startswith('-')
            c = c.removeprefix('-')
            field = col2field.get(c, c)
            records.sort(
                key=lambda r: (str(type(r.get(field))), r.get(field)),
                reverse=reverse,
            )

    sep = "  "
    header = sep.join(c.ljust(w) for c, w in columns.items())
    underline = sep.join("-" * w for c, w in columns.items())
    print(theme.title(header))
    print(theme.separator(underline))
    for record in records:
        row = sep.join(
            value2str(record.get(col2field.get(c, c)), theme, width=w)
            for c, w in columns.items()
        )
        print(row)


if __name__ == "__main__":
    main()
