#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = [
#   "python-debian",
# ]
# ///
"""
List all packages in an APT repository.

Does not verify GPG signatures.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import urllib.request
from dataclasses import dataclass, field
from functools import cached_property
from io import BytesIO
from operator import attrgetter
from typing import Iterator

from debian import deb822, debian_support


CACHE_DIR = pathlib.Path('~/.cache/list-repo-packages').expanduser()


parser = argparse.ArgumentParser(
    description="List all packages in an APT repository"
)
parser.add_argument("uri")
parser.add_argument("suite", nargs='+')

group = parser.add_mutually_exclusive_group()
group.add_argument(
    "--list-packages",
    action="store_const",
    dest='action',
    const='list-packages',
    default='list-packages',
    help=(
        "List the newest available version of each package for each suite,"
        " component, and architecture"
    ),
)
group.add_argument(
    "--compare-suites",
    action="store_const",
    dest='action',
    const='compare-suites',
    help=(
        "When a package is available in multiple suites, compare the versions"
    ),
)


def warn(msg) -> None:
    print(msg, file=sys.stderr)


def fetch(url: str) -> bytes:
    with urllib.request.urlopen(url) as fp:
        return fp.read()


def fetch_cached(url: str, key: str) -> bytes:
    cache_file = CACHE_DIR.joinpath(key)
    if cache_file.exists():
        return cache_file.read_bytes()
    data = fetch(url)
    cache_file.parent.mkdir(parents=True, exist_ok=True)
    cache_file.with_suffix('.new').write_bytes(data)
    cache_file.with_suffix('.new').rename(cache_file)
    return data


@dataclass
class ReleaseFile:
    uri: str
    suite: str

    @property
    def url(self) -> str:
        return f'{self.uri}/dists/{self.suite}/InRelease'

    @cached_property
    def data(self) -> bytes:
        return fetch(self.url)

    @cached_property
    def _release(self) -> deb822.Release:
        release = deb822.Release(BytesIO(self.data))
        assert release['Suite'] == self.suite
        assert release['Acquire-By-Hash'] == 'yes'
        assert 'SHA256' in release
        return release

    @cached_property
    def packages_files(self) -> list[PackagesFile]:
        return [
            PackagesFile(
                self.uri,
                self.suite,
                path=p["name"],
                sha256=p["sha256"],
                size=p["size"],
            )
            for p in self._release['SHA256']
            if p['name'].endswith('/Packages')
        ]

    @cached_property
    def all_packages(self) -> list[Package]:
        return [
            pkg
            for pf in self.packages_files
            for pkg in pf.packages
        ]

    @cached_property
    def package_set(self) -> PackageSet:
        return PackageSet(self.all_packages)


@dataclass
class PackagesFile:
    uri: str
    suite: str

    path: str = field(kw_only=True)
    sha256: str = field(kw_only=True, repr=False)
    size: str = field(kw_only=True, repr=False)

    @property
    def url_by_name(self) -> str:
        return f'{self.uri}/dists/{self.suite}/{self.path}'

    @property
    def url_by_hash(self) -> str:
        p = self.path.removesuffix('/Packages')
        return (
            f'{self.uri}/dists/{self.suite}/{p}/by-hash/SHA256/{self.sha256}'
        )

    @property
    def component(self) -> str:
        head, _, tail = self.path.partition('/')
        assert tail.startswith('binary-')
        return head

    @property
    def arch(self) -> str:
        head, _, tail = self.path.partition('/')
        assert tail.startswith('binary-')
        return tail.removeprefix('binary-').partition('/')[0]

    @cached_property
    def data(self) -> bytes:
        if self.size == '0':
            return b''
        return fetch_cached(self.url_by_hash, self.sha256)

    @cached_property
    def packages(self) -> list[Package]:
        return [
            Package(pkg, self.suite, self.component, self.arch)
            for pkg in deb822.Packages.iter_paragraphs(
                self.data, use_apt_pkg=False
            )
        ]


@dataclass
class Package:
    _pkg: deb822.Packages
    suite: str
    component: str
    arch: str

    def __post_init__(self) -> None:
        arch = self._pkg['Architecture']
        if self.arch != arch:
            # should we warn about this?
            # I've seen .../binary-all/Packages contain Architecture: amd64.
            # and other weirdness
            if arch != 'all':
                warn(
                    f'Architecture mismatch for {self.name} {self.version}'
                    f' in {self.suite}/{self.component}: {self.arch} != {arch}'
                )
            self.arch = arch

    @property
    def name(self) -> str:
        return self._pkg['Package']

    @property
    def version(self) -> debian_support.Version:
        return self._pkg.get_version()

    @property
    def source(self) -> str | None:
        return self._pkg.source

    @property
    def source_version(self) -> debian_support.Version:
        return self._pkg.source_version


type PackageName = str
type Arch = str
type Suite = str
type Component = str
type PackageKey = tuple[PackageName, Arch, Suite, Component]


@dataclass
class PackageSet:
    packages: list[Package]

    latest: dict[PackageKey, Package] = field(init=False, repr=False)
    by_name: dict[PackageName, list[Package]] = field(init=False, repr=False)

    def __post_init__(self) -> None:
        self.latest = {}
        for pkg in self.packages:
            key = (pkg.name, pkg.arch, pkg.suite, pkg.component)
            missing = key not in self.latest
            newer = not missing and pkg.version > self.latest[key].version
            if missing or newer:
                self.latest[key] = pkg
        self.by_name = {}
        for pkg in self:
            self.by_name.setdefault(pkg.name, []).append(pkg)

    def __iter__(self) -> Iterator[Package]:
        return iter(
            sorted(
                self.latest.values(),
                key=attrgetter(
                    'name', 'version', 'suite', 'component', 'arch'
                ),
            )
        )


def main() -> None:
    args = parser.parse_args()

    all_packages = []
    for suite in args.suite:
        release = ReleaseFile(args.uri, suite)
        all_packages += release.all_packages
    package_set = PackageSet(all_packages)
    match args.action:
        case 'list-packages':
            for pkg in package_set:
                print(
                    pkg.name,
                    pkg.version,
                    pkg.suite + '/' + pkg.component,
                    pkg.arch,
                )
        case 'compare-suites':
            package_names = sorted(package_set.by_name)
            for name in package_names:
                suites = {
                    pkg.suite + '/' + pkg.component
                    for pkg in package_set.by_name[name]
                }
                if len(suites) > 1:
                    print(name)
                    for pkg in sorted(
                        package_set.by_name[name],
                        key=attrgetter(
                            'version', 'suite', 'component', 'arch'
                        ),
                    ):
                        print(
                            ' ',
                            pkg.suite + '/' + pkg.component,
                            pkg.arch,
                            pkg.version,
                        )


if __name__ == "__main__":
    try:
        main()
    except Exception:
        import pdb
        import readline  # noqa
        import traceback
        traceback.print_exc()
        pdb.post_mortem()
