#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = [
#   "python-debian",
# ]
# ///
"""
List all packages in an APT repository.

Does not verify GPG signatures.
"""

from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys
import urllib.request
from contextlib import suppress
from dataclasses import dataclass, field
from functools import cached_property
from io import BytesIO
from operator import attrgetter
from typing import Any, Iterator

from debian import deb822, debian_support

CACHE_DIR = pathlib.Path('~/.cache/list-repo-packages').expanduser()
# Cache directory contains
# - Packages files named by their SHA256 hash
# - Symlinks to Packages files named after the URL without scheme with slashes
#   converted to underscores (like the filenames in /var/lib/apt/lists)
# - InRelease files named after the URL without scheme with slashes converted
#   to underscores (like the filenames in /var/lib/apt/lists), which are
#   written but never read.


parser = argparse.ArgumentParser(
    description="List all packages in an APT repository"
)
parser.add_argument("uri")
parser.add_argument("suite", nargs='+')
parser.add_argument(
    "-v", "--verbose",
    help='provide more information',
    action='store_true',
)
parser.add_argument(
    "-n", "--dry-run",
    help=(
        "(when combined with --download) print the URL instead of downloading"
    ),
    action='store_true',
)
parser.add_argument(
    "-p", "--packages",
    help='limit output to named packages (comma-separated)',
)
parser.add_argument(
    "-a", "--architectures",
    help='limit output to listed architectures (comma-separated)',
)
parser.add_argument(
    "-c", "--components",
    help='limit output to listed components (comma-separated)',
)
parser.add_argument(
    "-l", "--hyperlinks",
    action='store_true',
    help='link package versions to downloadable package files',
)

group = parser.add_mutually_exclusive_group()
group.add_argument(
    "--list-packages",
    action="store_const",
    dest='action',
    const='list-packages',
    default='list-packages',
    help=(
        "List the newest available version of each package for each suite,"
        " component, and architecture"
    ),
)
group.add_argument(
    "--compare-suites",
    action="store_const",
    dest='action',
    const='compare-suites',
    help=(
        "When a package is available in multiple suites, compare the versions"
    ),
)
group.add_argument(
    "-d", "--download",
    action="store_const",
    dest='action',
    const='download',
    help="Download the latest version of the package",
)


def warn(msg) -> None:
    print(msg, file=sys.stderr)


def urlify(text: Any, link: str) -> str:
    return f'\033]8;;{link}\033\\{text}\033]8;;\033\\'


def do_not_urlify(text: Any, link: str) -> str:
    return text


def fetch(url: str) -> bytes:
    with urllib.request.urlopen(url) as fp:
        data = fp.read()
    # write-only "cache", for debugging
    key = url2filename(url)
    cache_file = CACHE_DIR.joinpath(key)
    assert '/' not in key
    assert '..' not in key
    cache_file.parent.mkdir(parents=True, exist_ok=True)
    cache_file.with_suffix('.new').write_bytes(data)
    cache_file.with_suffix('.new').rename(cache_file)
    return data


def url2filename(url: str) -> str:
    return url.partition(':')[-1].lstrip('/').replace('/', '_')


def fetch_cached(url: str, key: str, symlink: str | None = None) -> bytes:
    assert '/' not in key
    assert '..' not in key
    cache_file = CACHE_DIR.joinpath(key)
    if cache_file.exists():
        data = cache_file.read_bytes()
    else:
        data = fetch(url)
        cache_file.parent.mkdir(parents=True, exist_ok=True)
        cache_file.with_suffix('.new').write_bytes(data)
        cache_file.with_suffix('.new').rename(cache_file)
    if symlink:
        symlink_name = url2filename(symlink)
        assert '/' not in symlink_name
        assert '..' not in symlink_name
        symlink_file = CACHE_DIR.joinpath(symlink_name)
        if not (
            symlink_file.exists()
            and symlink_file.is_symlink()
            and symlink_file.readlink() == cache_file.name
        ):
            with suppress(FileNotFoundError):
                symlink_file.unlink()
            symlink_file.symlink_to(cache_file.name)
    return data


@dataclass
class ReleaseFile:
    uri: str
    suite: str

    @property
    def url(self) -> str:
        return f'{self.uri}/dists/{self.suite}/InRelease'

    @cached_property
    def data(self) -> bytes:
        return fetch(self.url)

    @cached_property
    def _release(self) -> deb822.Release:
        release = deb822.Release(BytesIO(self.data))
        assert release['Suite'] == self.suite
        assert release['Acquire-By-Hash'] == 'yes'
        assert 'SHA256' in release
        return release

    @cached_property
    def packages_files(self) -> list[PackagesFile]:
        return [
            PackagesFile(
                self.uri,
                self.suite,
                path=p["name"],
                sha256=p["sha256"],
                size=p["size"],
            )
            for p in self._release['SHA256']
            if p['name'].endswith('/Packages')
        ]

    @cached_property
    def all_packages(self) -> list[Package]:
        return [
            pkg
            for pf in self.packages_files
            for pkg in pf.packages
        ]

    @cached_property
    def package_set(self) -> PackageSet:
        return PackageSet(self.all_packages)


@dataclass
class PackagesFile:
    uri: str
    suite: str

    path: str = field(kw_only=True)
    sha256: str = field(kw_only=True, repr=False)
    size: str = field(kw_only=True, repr=False)

    @property
    def url_by_name(self) -> str:
        return f'{self.uri}/dists/{self.suite}/{self.path}'

    @property
    def url_by_hash(self) -> str:
        p = self.path.removesuffix('/Packages')
        return (
            f'{self.uri}/dists/{self.suite}/{p}/by-hash/SHA256/{self.sha256}'
        )

    @property
    def component(self) -> str:
        head, _, tail = self.path.partition('/')
        assert tail.startswith('binary-')
        return head

    @property
    def arch(self) -> str:
        head, _, tail = self.path.partition('/')
        assert tail.startswith('binary-')
        return tail.removeprefix('binary-').partition('/')[0]

    @cached_property
    def data(self) -> bytes:
        if self.size == '0':
            return b''
        return fetch_cached(
            self.url_by_hash, self.sha256, symlink=self.url_by_name
        )

    @cached_property
    def packages(self) -> list[Package]:
        return [
            Package(pkg, self.uri, self.suite, self.component, self.arch)
            for pkg in deb822.Packages.iter_paragraphs(
                self.data, use_apt_pkg=False
            )
        ]


@dataclass
class Package:
    _pkg: deb822.Packages
    uri: str
    suite: str
    component: str
    arch: str

    def __post_init__(self) -> None:
        arch = self._pkg['Architecture']
        if self.arch != arch:
            # should we warn about this?
            # I've seen .../binary-all/Packages contain Architecture: amd64.
            # and other weirdness
            if arch != 'all':
                warn(
                    f'Architecture mismatch for {self.name} {self.version}'
                    f' in {self.suite}/{self.component}: {self.arch} != {arch}'
                )
            self.arch = arch

    @property
    def name(self) -> str:
        return self._pkg['Package']

    @property
    def version(self) -> debian_support.Version:
        return self._pkg.get_version()

    @property
    def source(self) -> str | None:
        return self._pkg.source

    @property
    def source_version(self) -> debian_support.Version:
        return self._pkg.source_version

    @property
    def filename(self) -> str:
        return self._pkg['Filename']

    @property
    def url(self) -> str:
        return f'{self.uri}/{self.filename}'

    @property
    def control_data(self) -> Iterator[tuple[str, str]]:
        for k, v in self._pkg.items():
            yield k, str(v)


type PackageName = str
type Arch = str
type Suite = str
type Component = str
type PackageKey = tuple[PackageName, Arch, Suite, Component]


@dataclass
class PackageSet:
    packages: list[Package]

    latest: dict[PackageKey, Package] = field(init=False, repr=False)
    by_name: dict[PackageName, list[Package]] = field(init=False, repr=False)

    def __post_init__(self) -> None:
        self.latest = {}
        for pkg in self.packages:
            key = (pkg.name, pkg.arch, pkg.suite, pkg.component)
            missing = key not in self.latest
            newer = not missing and pkg.version > self.latest[key].version
            if missing or newer:
                self.latest[key] = pkg
        self.by_name = {}
        for pkg in self:
            self.by_name.setdefault(pkg.name, []).append(pkg)

    def get_newest(self, name: str) -> Package:
        return max(self.by_name[name], key=attrgetter('version'))

    def __iter__(self) -> Iterator[Package]:
        return iter(
            sorted(
                self.latest.values(),
                key=attrgetter(
                    'name', 'version', 'suite', 'component', 'arch'
                ),
            )
        )


def main() -> None:
    args = parser.parse_args()

    packages = set((args.packages or '').split(',')) - {''}
    architectures = set((args.architectures or '').split(',')) - {''}
    components = set((args.components or '').split(',')) - {''}

    maybe_urlify = urlify if args.hyperlinks else do_not_urlify

    all_packages = []
    for suite in args.suite:
        release = ReleaseFile(args.uri, suite)
        all_packages += release.all_packages
    package_set = PackageSet(all_packages)
    match args.action:
        case 'list-packages':
            for pkg in package_set:
                if packages and pkg.name not in packages:
                    continue
                if architectures and pkg.arch not in architectures:
                    continue
                if components and pkg.component not in components:
                    continue
                print(
                    pkg.name,
                    maybe_urlify(pkg.version, pkg.url),
                    pkg.suite + '/' + pkg.component,
                    pkg.arch,
                )
                if args.verbose:
                    for k, v in pkg.control_data:
                        space = ' '
                        if not v or v.startswith('\n'):
                            space = ''
                        if k == 'Filename':
                            v = maybe_urlify(v, pkg.url)
                        v = v.replace('\n', '\n  ')
                        print(f'  {k}:{space}{v}')
                    print()
        case 'compare-suites':
            if packages:
                package_names = sorted(set(package_set.by_name) & packages)
            else:
                package_names = sorted(package_set.by_name)
            for name in package_names:
                suites = {
                    pkg.suite + '/' + pkg.component
                    for pkg in package_set.by_name[name]
                    if (not architectures or pkg.arch in architectures)
                    and (not components or pkg.component in components)
                }
                if len(suites) > 1:
                    print(name)
                    for pkg in sorted(
                        package_set.by_name[name],
                        key=attrgetter(
                            'version', 'suite', 'component', 'arch'
                        ),
                    ):
                        if architectures and pkg.arch not in architectures:
                            continue
                        if components and pkg.component not in components:
                            continue
                        print(
                            ' ',
                            pkg.suite + '/' + pkg.component,
                            pkg.arch,
                            maybe_urlify(pkg.version, pkg.url),
                        )
        case 'download':
            if not packages:
                parser.error('Please specify -p PACKAGE_NAME')
            for name in packages:
                pkg = package_set.get_newest(name)
                print(maybe_urlify(pkg.url, pkg.url))
                if not args.dry_run:
                    subprocess.run(['wget', pkg.url])


if __name__ == "__main__":
    try:
        main()
    except Exception:
        import pdb
        import readline  # noqa
        import traceback
        traceback.print_exc()
        pdb.post_mortem()
