#!/bin/sh
# the point of this script is to mute the builtin laptop speakers even when
# youre currently playing sound through bluetooh headphones and therefore
# cannot use the mute button.

pactl list short sinks | while read index name etc; do
    case $name in
        alsa_output.pci-*)
            pactl set-sink-mute $index 1
            ;;
    esac
done
