#!/bin/bash
where=~/src/neomutt
if [ -x $where/neomutt ]; then
    if ! [ -e ~/.local/share/locale/lt/LC_MESSAGES/neomutt.mo ]; then
      mkdir -p ~/.local/share/locale/lt/LC_MESSAGES
      ln -sr $where/po/lt.gmo ~/.local/share/locale/lt/LC_MESSAGES/neomutt.mo
    fi
    if ! [ -e $where/po/lt.gmo ] || ! [ $where/po/lt.gmo -nt $where/po/lt.po ]; then
      make -C $where/po lt.gmo
    fi
    export TEXTDOMAINDIR=~/.local/share/locale/
    exec $where/neomutt "$@"
else
    exec /usr/bin/mutt "$@"
fi
