#!/bin/sh

PIPSI_ENV=~/.local/venvs/pipsi
PIPSI_BINDIR=~/.local/bin
PIPSI_PYTHON=python3
PIPSI_VENV=venv
# use virtualenv for python2

# bootstrap
if ! [ -x $PIPSI_ENV/bin/pipsi ]; then
    $PIPSI_PYTHON -m $PIPSI_VENV $PIPSI_ENV || exit 1
    $PIPSI_ENV/bin/pip install -U pip || exit 1
    $PIPSI_ENV/bin/pip install pipsi || exit 1
fi
if ! [ -x $PIPSI_BINDIR/pipsi ]; then
    ln -sf $PIPSI_ENV/bin/pipsi $PIPSI_BINDIR/pipsi || exit 1
fi

# run the real pipsi
exec $PIPSI_BINDIR/pipsi "$@"
