#!/bin/bash

# we have choices here: do we want PIPX_ENV to be inside PIPX_ENV_DIR or not?
# - inside: pipx upgrade pipx works, pipx reinstall-all breaks horribly
# - outside: pipx reinstall-all works, pipx cannot upgrade itself
PIPX_ENV=~/.local/pipx/itself
PIPX_ENV_DIR=~/.local/pipx/venvs
PIPX_SHARED_ENV=~/.local/pipx/shared
PIPX_BINDIR=~/.local/bin
PIPX_PYTHON=${PIPX_PYTHON:-python3}

if ! [ -x $PIPX_ENV/bin/pipx ]; then
    # bootstrap: let's install pipx manually
    $PIPX_PYTHON -c 'import sys; exit(sys.version_info < (3, 6))' || {
        echo "python3 is too old, trying python3.6"
        PIPX_PYTHON=python3.6
    }
    echo "bootstrapping pipx"
    $PIPX_PYTHON -m venv $PIPX_ENV || exit 1
    $PIPX_ENV/bin/pip install -U pip || exit 1
    $PIPX_ENV/bin/pip install -U pipx || exit 1
fi
if ! [ -x $PIPX_SHARED_ENV/bin/pip ]; then
    # bootstrap: create the shared venv manually and apply the workaround for
    # https://github.com/pipxproject/pipx/issues/386#issuecomment-618961187
    $PIPX_PYTHON -m venv $PIPX_SHARED_ENV || exit 1
    $PIPX_SHARED_ENV/bin/pip install -I pip setuptools wheel || exit 1
fi
if ! [ -L $PIPX_BINDIR/pipx ] || ! [ $PIPX_BINDIR/pipx -ef $PIPX_ENV/bin/pipx ] ; then
    # bootstrap: make sure we have a symlink to pipx on our PATH
    test -d $PIPX_BINDIR || mkdir -p $PIPX_BINDIR
    ln -sf $PIPX_ENV/bin/pipx $PIPX_BINDIR/pipx || exit 1
fi
if [ $PIPX_ENV = $PIPX_ENV_DIR/pipx ] && ! [ -f $PIPX_ENV/pipx_metadata.json ]; then
    # bootstrap: create metadata so pipx is able to upgrade itself
    $PIPX_BINDIR/pipx install --force pipx || exit 1
fi

if [ "$1" = "--upgrade" ]; then
    $PIPX_ENV/bin/pip install -U pipx
    exit
fi

# integrate with new-changelog-entry
nl=$'\n  '
case "$1" in
    --changelog)
        shift
        new-changelog-entry "su - $USER${nl}  pipx $*"
        echo
        ;;
    --changelog-only)
        shift
        new-changelog-entry "su - $USER${nl}  pipx $*"
        exit
        ;;
    --changelog-append)
        shift
        new-changelog-entry -a "  pipx $*"
        echo
        ;;
    --changelog-append-only)
        shift
        new-changelog-entry -a "  pipx $*"
        exit
        ;;
esac

# run the real pipx
exec $PIPX_BINDIR/pipx "$@"
