#!/bin/sh
if [ -n "$SSH_AGENT_PID" ]; then
    # See if ssh-agent has any identities, and if not, add some
    ssh-add -l > /dev/null || ssh-add
fi
fuser -s -n tcp 6667 || { ~/bin/irc-tunnel & sleep 1; }
if [ -x ~/.local/bin/jhbuild ] && [ -x ~/jhbuild/install/bin/polari ] ; then
    ~/.local/bin/jhbuild run polari
elif [ -x /usr/bin/flatpak ] && flatpak info org.gnome.Polari >/dev/null 2>&1; then
    flatpak run org.gnome.Polari
else
    /usr/bin/polari
fi
