#!/bin/sh
test -f ~/src/deployments/fabfile.py || {
    echo "~/src/deployments/fabfile.py is missing, please run the following command:" 1>&2
    echo 1>&2
    echo "  cd ~/src && git clone git@github.com:ProgrammersOfVilnius/deployments" 1>&2
    exit 1
}
fab -f ~/src/deployments/fabfile.py "$@"
