#!/bin/bash
# Replaced by https://github.com/mgedmin/ppa-copy-packages

PPA_OWNER=gtimelog-dev
PPA_NAME=ppa
SOURCE_SERIES=xenial    # aka 16.04 LTS
TARGET_SERIES=(
    bionic              # aka 18.04 LTS
    cosmic              # aka 18.10
    disco               # aka 19.04
)
PACKAGES=(
    gtimelog
)

if [ -z "$(command -v ppa-copy-packages 2>/dev/null)" ]; then
    echo "ppa-copy-packages missing; install with pipx install ppa-copy-packages" 1>&2
    exit 1
fi
set -x
ppa-copy-packages -O $PPA_OWNER -N $PPA_NAME -s $SOURCE_SERIES -t "${TARGET_SERIES[@]}" -p "${PACKAGES[@]}" "$@"
