#!/bin/bash
# There are some packages I still need on Ubuntu

PPA_OWNER=mgedmin
PPA_NAME=ppa
SOURCE_SERIES=focal     # aka 20.04 LTS
TARGET_SERIES=(
    jammy               # aka 22.04 LTS
    noble               # aka 24.04 LTS
    plucky              # aka 25.04
    questing            # aka 25.10
    resolute            # aka 26.04 LTS
)
PACKAGES=(
    pwsafe
)

if [ -z "$(command -v ppa-copy-packages 2>/dev/null)" ]; then
    echo "ppa-copy-packages missing; install with pipx install ppa-copy-packages" 1>&2
    exit 1
fi
set -x
ppa-copy-packages -O $PPA_OWNER -N $PPA_NAME -s $SOURCE_SERIES -t "${TARGET_SERIES[@]}" -p "${PACKAGES[@]}" "$@"
