#!/usr/bin/python3
import sys
import argparse

# sudo apt install python3-yaml
import yaml


def main():
    parser = argparse.ArgumentParser(description="Pretty-print YAML")
    parser.add_argument('filenames', metavar='file', nargs='*', default=['-'])
    args = parser.parse_args()
    doit = pretty_print
    for fn in args.filenames:
        if fn == '-':
            doit(sys.stdin, fn)
        else:
            with open(fn) as f:
                doit(f, fn)


def pretty_print(fp, filename):
    yaml.safe_dump(yaml.safe_load(fp), sys.stdout,
                   default_flow_style=False)


if __name__ == '__main__':
    main()
