#!/bin/bash

pull=no
builddeps=no

for arg; do
    case "$arg" in
        -h|--help)
            echo "Usage: $(basename "$0") [options]"
            echo
            echo "Options:"
            echo "  --pull              git pull before building"
            echo "  --build-deps        sudo apt install build dependencies"
            exit
            ;;
        --pull)
            pull=yes
            ;;
        --build-deps)
            builddeps=yes
            ;;
        *)
            echo "unrecognized argument: $arg" 1>&2
            exit 1
            ;;
    esac
done

FEATURES=(
    # debian's mutt (1.6.2-3) does this:
    --with-mailpath=/var/mail
    --enable-compressed
    --enable-debug
    --enable-fcntl
    --enable-hcache
    --enable-gpgme
    --enable-imap
    --enable-smtp
    --enable-pop
    --enable-sidebar
    --enable-nntp
    --enable-notmuch
    --disable-fmemopen
    --with-curses
    --with-gnutls
    --with-gss
    --with-idn
    --with-mixmaster
    --with-sasl
    --without-gdbm
    --without-bdb
    --without-qdbm
)

BUILDDEPS=(
    # debian's mutt (1.6.2-3) depends on this:
    debhelper
    dh-autoreconf
    docbook-xml
    docbook-xsl
    gawk
    gettext
    libgnutls28-dev
    libgpgme11-dev
    libidn11-dev
    libkrb5-dev
    libnotmuch-dev
    libncurses5-dev
    libncursesw5-dev
    libsasl2-dev
    libtokyocabinet-dev
    pkg-config
    w3m
    xsltproc
    zlib1g-dev
)

cd ~/src/neomutt || {
    echo "To get mutt sources do" 1>&2
    echo "  git clone https://github.com/neomutt/neomutt ~/src/neomutt" 1>&2
    read -r -p "Would you like me to run that for you now? [y/N] " answer
    if [ "$answer" = "y" ]; then
        git clone https://github.com/neomutt/neomutt ~/src/neomutt && cd ~/src/neomutt || exit 1
    else
        exit 1
    fi
}

if [ $pull = yes ]; then
    git pull
fi

if [ $builddeps = yes ]; then
    sudo apt install "${BUILDDEPS[@]}"
fi

./prepare "${FEATURES[@]}" && make clean && make -j4
