#!/bin/bash

pull=no
builddeps=no
asan=no

for arg; do
    case "$arg" in
        -h|--help)
            echo "Usage: $(basename "$0") [options]"
            echo
            echo "Options:"
            echo "  --pull              git pull before building"
            echo "  --build-deps        sudo apt install build dependencies"
            echo "  --asan              build with ASAN support (slower)"
            exit
            ;;
        --pull)
            pull=yes
            ;;
        --build-deps)
            builddeps=yes
            ;;
        --asan)
            asan=yes
            ;;
        *)
            echo "unrecognized argument: $arg" 1>&2
            exit 1
            ;;
    esac
done

FEATURES=(
    # I think debhelper implicitly adds this; anyway I need it to look for
    # mutt_dotlock in /usr/bin/ instead of /usr/local/bin/ and config in
    # /etc/Muttrc instead of /usr/local/etc/ or /usr/etc/
    "--prefix=/usr"
    "--sysconfdir=/etc"
    # Upstream switched from autoconf to autosetup and now I'm inventing stuff
    # on my own
    "--with-mailpath=/var/mail"
    --mixmaster
    --gnutls
    --gpgme
    --gss
    --sasl
    --lua
    --notmuch
    --tokyocabinet
    --full-doc
)

if [ $asan = yes ]; then
    # I keep finding bugs, so let's try to find MORE BUGS!
    FEATURES+=(--asan)
fi

BUILDDEPS=(
    # Ubuntu's mutt (1.8.3+neomutt20170609-2build1) depends on this:
    debhelper
    dh-autoreconf
    dh-lua
    docbook-xml
    docbook-xsl
    gawk
    gettext
    libgnutls28-dev
    libgpgme11-dev
    libidn11-dev
    libkrb5-dev
    libnotmuch-dev
    libncurses5-dev
    libncursesw5-dev
    libsasl2-dev
    libtokyocabinet-dev
    pkg-config
    w3m
    xsltproc
    zlib1g-dev
    # configure fails trying to run xmlcatalog
    libxml2-utils
)

if [ $builddeps = yes ]; then
    sudo apt install "${BUILDDEPS[@]}"
fi

autoclone ~/src/neomutt https://github.com/neomutt/neomutt
cd ~/src/neomutt || exit 1

if [ $pull = yes ]; then
    git pull
fi

./configure "${FEATURES[@]}" && make clean && make -j4
