#!/bin/bash
set -eu

ruby=yes
pull=no
clean=no
builddeps=no
for arg; do
    case "$arg" in
        -h|--help)
            echo "Usage: $0 [options]"
            echo "Options:"
            echo "  --pull              git pull before building"
            echo "  --clean             git clean -dfx before building"
            echo "  --build-deps        sudo apt install build dependencies"
            echo "  --no-ruby           disable :ruby support"
            exit
            ;;
        --no-ruby)
            ruby=no
            ;;
        --clean)
            clean=yes
            ;;
        --pull)
            pull=yes
            ;;
        --build-deps)
            builddeps=yes
            ;;
        *)
            echo "unrecognized argument: $arg" 1>&2
            exit 1
            ;;
    esac
done

COMPILED_BY="Marius Gedminas <marius@gedmin.as>"
FEATURES=(
    "--with-features=huge"      # yum, features
    "--enable-multibyte"        # vim is *crippled* without this!
                                # (BTW 'big' implies this)
    "--enable-python3interp"    # most of my plugins use this
    "--enable-gpm"              # heh retro
    "--enable-terminal"         # fancy!
#   "--enable-perlinterp"       # ruby + perl = segfault
    # taken from ubuntu's debian/rules
    "--with-x"
    "--enable-xim"
    "--enable-gui=gtk3"
    "--disable-gtk2-check"
    "--enable-gnome-check"
    "--disable-motif-check"
    "--disable-athena-check"
    "--disable-fontset"
    "--enable-fail-if-missing"
)
if [ $ruby = yes ]; then
    FEATURES+=("--enable-rubyinterp")   # Command-T wants this
else
    FEATURES+=("--disable-rubyinterp")
fi


BUILDDEPS=(
    # from https://salsa.debian.org/vim-team/vim/blob/debian/sid/debian/control
    # (I picked a subset that looks reasonable to me)
    autoconf
    cscope
    libacl1-dev
    libgpmg1-dev
    libgtk-3-dev
    libselinux1-dev
    libncurses-dev
    libxaw7-dev
    libxpm-dev
    libxt-dev
    python3-dev
    ruby-dev
    # I remember builds failing for lack of libssl-dev
    libssl-dev
)

if [ $builddeps = yes ]; then
    sudo apt install "${BUILDDEPS[@]}"
fi

autoclone ~/src/vim https://github.com/vim/vim/
cd ~/src/vim || exit 1
if [ $pull = yes ]; then
    git pull
fi
rm -f src/auto/config.cache
if [ $clean = yes ]; then
    git clean -dfx
fi

# let's not let vim's ./configure see ~/bin/python*
export PATH=/usr/lib/ccache:/usr/bin:/bin
export CFLAGS="-g"
if ! (./configure "${FEATURES[@]}" --with-compiledby="$COMPILED_BY" && make -j8); then
    echo "Consider $0 --build-deps" 1>&2
    exit 1
fi
