#!/bin/bash
set -eu

gui=gtk3
ruby=yes
terminal=yes
termtruecolor=no
pull=no
builddeps=no
for arg; do
    case "$arg" in
        -h|--help)
            echo "Usage: $0 [options]"
            echo "Options:"
            echo "  --pull              git pull before building"
            echo "  --build-deps        sudo apt install build dependencies"
            echo "  --gtk2              build for GTK+ 2 (default: GTK+ 3)"
            echo "  --no-ruby           disable :ruby support"
            echo "  --no-terminal       disable :terminal support"
            echo "  --termtruecolor     enable truecolor support in xterm (default since 7.4.1784)"
            exit
            ;;
        --no-ruby)
            ruby=no
            ;;
        --no-terminal)
            terminal=no
            ;;
        --gtk2)
            gui=gnome2
            ;;
        --termtruecolor)
            termtruecolor=yes
            ;;
        --pull)
            pull=yes
            ;;
        --build-deps)
            builddeps=yes
            ;;
        *)
            echo "unrecognized argument: $arg" 1>&2
            exit 1
            ;;
    esac
done

COMPILED_BY="Marius Gedminas <marius@gedmin.as>"
FEATURES=(
    "--with-features=huge"  # yum, features
    "--enable-multibyte"    # vim is *crippled* without this!
                            # (BTW 'big' implies this)
    "--enable-pythoninterp=dynamic" # most of my plugins use this
    "--enable-python3interp=dynamic"
    "--enable-cscope"
    "--enable-gpm"
)
if [ $ruby = yes ]; then
    FEATURES+=("--enable-rubyinterp")   # Command-T wants this
else
    FEATURES+=("--disable-rubyinterp")
fi
if [ $terminal = yes ]; then
    FEATURES+=("--enable-terminal")
else
    FEATURES+=("--disable-terminal")
fi
#FEATURES+=("--enable-perlinterp")  # ruby + perl = segfault
#FEATURES+=("--enable-luainterp")
#FEATURES+=("--enable-mzschemeinterp")
#FEATURES+=("--enable-tcpinterp")

if [ $termtruecolor = yes ]; then
    FEATURES+=("--enable-termtruecolor")
fi

# taken from ubuntu's debian/rules
FEATURES+=("--with-x")
FEATURES+=("--enable-xim")
FEATURES+=("--enable-gui=$gui")
FEATURES+=("--disable-gtk2-check")
FEATURES+=("--enable-gnome-check")
FEATURES+=("--disable-motif-check")
FEATURES+=("--disable-athena-check")
FEATURES+=("--disable-fontset")
FEATURES+=("--enable-fail-if-missing")

BUILDDEPS=(
    # from https://salsa.debian.org/vim-team/vim/blob/debian/sid/debian/control
    # (I picked a subset that looks reasonable to me)
    autoconf
    cscope
    libacl1-dev
    libgpmg1-dev
    libgtk-3-dev
    libncurses-dev
    python3-dev
    ruby-dev
    # I remember builds failing for lack of libssl-dev
    libssl-dev
)

# let's not let vim see ~/.venv/bin/python
export PATH=/usr/lib/ccache:/usr/bin:/bin

CFLAGS="-g"

if [ $builddeps = yes ]; then
    sudo apt install "${BUILDDEPS[@]}"
fi

test -d ~/src/vim || {
    echo "To get vim sources do" 1>&2
    echo 1>&2
    echo "  git clone https://github.com/vim/vim/ ~/src/vim" 1>&2
    echo 1>&2
    read -r -p "Would you like me to run that for you now? [y/N] " answer
    if [ "$answer" = "y" ]; then
        git clone https://github.com/vim/vim ~/src/vim || exit 1
    else
        exit 1
    fi
}
cd ~/src/vim
if [ $pull = yes ]; then
    git pull
fi
rm -f src/auto/config.cache
CFLAGS="$CFLAGS" ./configure "${FEATURES[@]}" --with-compiledby="$COMPILED_BY" \
&& make -j4 || {
    echo "Consider" 1>&2
    echo "  sudo apt-get build-dep vim" 1>&2
    echo "  sudo apt-get install ruby-dev libssl-dev" 1>&2
    exit 1
}
# for that matter, if you get
#   checking if compile and link flags for Python are sane... no: PYTHON DISABLED
# config.log says
#   /usr/bin/ld: cannot find -lssl
# the fix is to:
#   apt-get install libssl-dev

# also, if you get a vim without ruby support, make sure you
#   sudo apt-get install ruby-dev
# there's a sad bug in Ubuntu 12.10 where ruby1.8-dev Provides: ruby-dev (while
# the real ruby-dev Depends: ruby1.9.1-dev), and so apt-get build-dep vim
# doesn't notice you don't have the right header files
