#!/bin/sh
set -e

gui=gtk3
ruby=yes
termtruecolor=no
pull=no
for arg; do
    case "$arg" in
        -h|--help)
            echo "Usage: $0 [options]"
            echo "Options:"
            echo "  --pull              git pull before building"
            echo "  --gtk2              build for GTK+ 2 (default: GTK+ 3)"
            echo "  --no-ruby           disable :ruby support"
            echo "  --termtruecolor     enable truecolor support in xterm (default since 7.4.1784)"
            exit
            ;;
        --no-ruby)
            ruby=no
            ;;
        --gtk2)
            gui=gnome2
            ;;
        --termtruecolor)
            termtruecolor=yes
            ;;
        --pull)
            pull=yes
            ;;
        *)
            echo "unrecognized argument: $arg" 1>&2
            exit 1
            ;;
    esac
done

COMPILED_BY="Marius Gedminas <marius@gedmin.as>"
FEATURES=
FEATURES="$FEATURES --with-features=huge"  # yum, features
FEATURES="$FEATURES --enable-multibyte"    # vim is *crippled* without this!
                                           # (BTW 'big' implies this)
FEATURES="$FEATURES --enable-pythoninterp=dynamic" # most of my plugins use this
FEATURES="$FEATURES --enable-python3interp=dynamic"
if [ $ruby = yes ]; then
    FEATURES="$FEATURES --enable-rubyinterp"   # Command-T wants this
else
    FEATURES="$FEATURES --disable-rubyinterp"
fi
#FEATURES="$FEATURES --enable-perlinterp"  # ruby + perl = segfault
#FEATURES="$FEATURES --enable-luainterp"
#FEATURES="$FEATURES --enable-mzschemeinterp"
#FEATURES="$FEATURES --enable-tcpinterp"
FEATURES="$FEATURES --enable-cscope"
FEATURES="$FEATURES --enable-gpm"

if [ $termtruecolor = yes ]; then
    FEATURES="$FEATURES --enable-termtruecolor"
fi

# taken from ubuntu's debian/rules
FEATURES="$FEATURES --with-x"
FEATURES="$FEATURES --enable-xim"
FEATURES="$FEATURES --enable-gui=$gui"
FEATURES="$FEATURES --disable-gtk2-check"
FEATURES="$FEATURES --enable-gnome-check"
FEATURES="$FEATURES --disable-motif-check"
FEATURES="$FEATURES --disable-athena-check"
FEATURES="$FEATURES --disable-fontset"
FEATURES="$FEATURES --enable-fail-if-missing"

# ubuntu 13.04 did something weird to the python config directory
if [ -x /usr/bin/dpkg-architecture ]; then
    FEATURES="$FEATURES --with-python-config-dir=/usr/lib/python2.7/config-$(dpkg-architecture -qDEB_HOST_MULTIARCH)"
fi

# let's not let vim see ~/.venv/bin/ptython
export PATH=/usr/lib/ccache:/usr/bin:/bin

#CFLAGS="-DUSE_FILE_CHOOSER" <-- buggy, fsync() with every keystroke is bad
CFLAGS="-g"

test -d ~/src/vim || {
    echo "To get vim sources do" 1>&2
    echo "  git clone https://github.com/vim/vim/ ~/src/vim" 1>&2
    exit 1
}
cd ~/src/vim
if [ $pull = yes ]; then
    git pull
fi
# make sure I have all the build-deps?
rm -f src/auto/config.cache
CFLAGS="$CFLAGS" ./configure $FEATURES --with-compiledby="$COMPILED_BY" \
&& make -j4 || {
    echo "Consider" 1>&2
    echo "  sudo apt-get build-dep vim" 1>&2
    echo "  sudo apt-get install ruby-dev libssl-dev" 1>&2
    exit 1
}
# for that matter, if you get
#   checking if compile and link flags for Python are sane... no: PYTHON DISABLED
# config.log says
#   /usr/bin/ld: cannot find -lssl
# the fix is to:
#   apt-get install libssl-dev

# also, if you get a vim without ruby support, make sure you
#   sudo apt-get install ruby-dev
# there's a sad bug in Ubuntu 12.10 where ruby1.8-dev Provides: ruby-dev (while
# the real ruby-dev Depends: ruby1.9.1-dev), and so apt-get build-dep vim
# doesn't notice you don't have the right header files
