#!/bin/bash
# Switch between svn://... and svn+ssh://... in subversion sandboxes
# Switch between https://github.com/... and git@github.com:... in git checkouts

if [ -d .svn ]; then
  url=`svn info $1|grep URL|cut -d ' ' -f 2-`
  schema=${url%%://*}
  rest=${url#*://}
  [ "$schema" != "svn" -a "$schema" != "http" ] && {
    echo "Repository URL doesn't begin with svn:// or http://"
    exit 1
  }
  rest=${rest/#source.schooltool.org\/svn/source.schooltool.org\/svn\/schooltool}
  svn switch --relocate $url svn+ssh://$rest $1
elif [ -e .git ]; then
  url=`git config remote.origin.url`
  case "$url" in
    https://gist.github.com/*.git)
      repo=${url##*/}
      newurl=git@gist.github.com:$repo
      ;;
    https://github.com/*)
      repo=${url#https://github.com/}
      newurl=git@github.com:${repo%.git}.git
      ;;
    git://github.com/*.git)
      repo=${url#git://github.com/}
      newurl=git@github.com:${repo%.git}.git
      ;;
    git@github.com:*|git@gist.github.com:*)
      # already editable
      exit 0
      ;;
    *)
      echo "Don't know the editable URL for $url" 1>&2
      exit 1
      ;;
  esac
  echo "$url -> $newurl"
  git config remote.origin.url $newurl
else
  echo "This is not a subversion or git working directory." 1>&2
  exit 1
fi
