#!/usr/bin/python3
# Loosely based on https://gist.github.com/XVilka/8346728

import sys
import shutil

bg_color = '\033[48;2;{r};{g};{b}m'
reset = '\033[m'


def main():
    max = shutil.get_terminal_size().columns - 1
    for n in range(max):
        r = 255 - (255 * n // max)
        g = 510 * n // max
        if g > 255:
            g = 510 - g
        b = 255 * n // max
        sys.stdout.write('{bg} '.format(bg=bg_color.format(r=r, g=g, b=b)))
    sys.stdout.write('{reset}\n'.format(reset=reset))


if __name__ == "__main__":
    main()
