#!/bin/sh
if ! test -d /sys/class/leds/tpacpi::power; then
    echo "This machine does not look like a ThinkPad" 1>&2
    exit 1
fi
if test -e /etc/sudoers.d/mg-turn-off-power-led; then
    sudo /usr/bin/systemctl start mg-turn-off-power-led
else
    pkexec sh -c 'echo 0 > /sys/class/leds/tpacpi::power/brightness'
fi
