#!/bin/sh
if ! test -d /sys/class/leds/platform::mute; then
    echo "No /sys/class/leds/platform::mute" 1>&2
    exit 1
fi
pkexec sh -c 'echo 0 > /sys/class/leds/platform::mute/brightness; echo 0 > /sys/class/leds/platform::micmute/brightness'
