#!/bin/bash
progname="${0##*/}"
python="${progname#virtual-bootstrap-}"
case "$python" in
    "")         python=python;;
    py[23])     python=python${python#py};;
    py2[0-9])   python=python2.${python#py2};;
    py3[0-9])   python=python3.${python#py3};;
    pypy|pypy3) ;;
    *)
        echo "Don't know what python interpreter $progname is supposed to use!"
        exit 1
        ;;
esac

if [ -n "$(netstat -tnl | grep ':3128 ')" ]; then
    export http_proxy=http://localhost:3128
    echo "Using a local Squid proxy."
fi
set -e
set -x
rm -rf develop-eggs .installed.cfg python
if [ -f .git/info/exclude ]; then
    if ! grep -q "^python/$" .git/info/exclude; then
        echo "python/" >> .git/info/exclude
    fi
fi
virtualenv -p ${python} python
python/bin/pip install -U setuptools
if [ -f bootstrap.py ]; then
    python/bin/python bootstrap.py
else
    python/bin/pip install -U zc.buildout
    python/bin/buildout bootstrap
fi
bin/buildout "$@"
