#!/bin/sh

autoclone ~/.weechat plato:git/dotweechat.git || exit 1

# do not run irc-tunnel if weechat is already running, that would kill its
# network connection!
if [ "$(pgrep -c weechat)" -lt 2 ]; then
    echo "starting IRC tunnel"
    irc-tunnel
else
    echo "another weechat already running, assuming IRC tunnel is up"
fi
if [ -x ~/opt/weechat/bin/weechat ]; then
    exec ~/opt/weechat/bin/weechat "$@"
else
    exec /usr/bin/weechat "$@"
fi
