#!/usr/bin/python3
# like watch, but better
import argparse
import os
import shlex


parser = argparse.ArgumentParser(
    description="watch the output of a command change"
)
# argparse.REMAINDER is not documented :/
# https://stackoverflow.com/questions/6488752/dont-parse-options-after-the-last-positional-argument/6671440#6671440
parser.add_argument(
    'command', nargs=argparse.REMAINDER,
    help='command to execute'
)
parser.add_argument(
    "-n", "--interval", metavar='SECONDS',
    help='seconds to wait between updates',
)


def main() -> None:
    args = parser.parse_args()
    if len(args.command) == 1:
        command = args.command[0]
    else:
        command = shlex.join(args.command)
    env = os.environ | {'FORCE_COLOR': '1', 'NO_HYPERLINKS': '1'}
    argv = ['watch', '-c']
    if args.interval is not None:
        argv += ['-n', str(args.interval)]
    argv += [command + ' | head-and-tail']
    os.execvpe(argv[0], argv, env)


if __name__ == "__main__":
    main()
